[project]
name = "ssmd"
version = "0.1.0"
description = "An elegant backend for interaction with ssmd database."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "alembic>=1.18.4",
  "fastapi>=0.135.2",
  "fastapi-limiter==0.1.6",
  "gunicorn>=25.3.0",
  "logging>=0.4.9.6",
  "psycopg2-binary>=2.9.11",
  "pwdlib[argon2]>=0.3.0",
  "pydantic>=2.12.5",
  "python-dotenv>=1.2.2",
  "python-jose[cryptography]>=3.5.0",
  "python-multipart>=0.0.22",
  "redis>=7.4.0",
  "sqlalchemy>=2.0.48",
  "uvicorn>=0.42.0",
]

[dependency-groups]
dev = ["pytest>=9.0.3", "pytest-sugar>=1.1.1", "httpx>=0.28.1"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["*Tests"]
python_functions = ["test_*"]
