"""Updated exam_subjects table to store class subject instead of global subjects

Revision ID: 0d8aec64f119
Revises: 786122f22820
Create Date: 2026-05-02 13:20:40.452148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d8aec64f119'
down_revision: Union[str, Sequence[str], None] = '786122f22820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam_subjects', 'class_subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_exam_subjects_subject_id'), table_name='exam_subjects')
    op.create_index('ix_exam_subjects_subject_id', 'exam_subjects', ['class_subject_id'], unique=False)
    op.drop_constraint(op.f('uq_exam_subjects'), 'exam_subjects', type_='unique')
    op.create_unique_constraint('uq_exam_subjects', 'exam_subjects', ['exam_id', 'class_subject_id'])
    op.drop_constraint(op.f('exam_subjects_subject_id_fkey'), 'exam_subjects', type_='foreignkey')
    op.create_foreign_key(None, 'exam_subjects', 'class_subjects', ['class_subject_id'], ['id'], ondelete='CASCADE')
    op.drop_column('exam_subjects', 'subject_id')
    op.alter_column('exams', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exams', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.add_column('exam_subjects', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exam_subjects', type_='foreignkey')
    op.create_foreign_key(op.f('exam_subjects_subject_id_fkey'), 'exam_subjects', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_exam_subjects', 'exam_subjects', type_='unique')
    op.create_unique_constraint(op.f('uq_exam_subjects'), 'exam_subjects', ['exam_id', 'subject_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_exam_subjects_subject_id', table_name='exam_subjects')
    op.create_index(op.f('ix_exam_subjects_subject_id'), 'exam_subjects', ['subject_id'], unique=False)
    op.alter_column('exam_subjects', 'class_subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
