"""Added exam status column to check the current status of an examination

Revision ID: 5203b02a8c1d
Revises: 8efdf9984b6d
Create Date: 2026-05-04 19:41:58.762160

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5203b02a8c1d"
down_revision: Union[str, Sequence[str], None] = "8efdf9984b6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exams",
        sa.Column("status", sa.String(), server_default="pending", nullable=True),
    )
    op.create_check_constraint(
        "ck_exam_status", "exams", "status IN ('pending', 'completed')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exams", "status")
    # ### end Alembic commands ###
