"""add staff_subjects

Revision ID: 5a3e27cbe26f
Revises: 
Create Date: 2026-04-14 16:23:17.218468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a3e27cbe26f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'subject_id', name='uq_staff_subjects')
    )
    op.create_index('ix_staff_subjects_staff_id', 'staff_subjects', ['staff_id'], unique=False)
    op.create_index('ix_staff_subjects_subject_id', 'staff_subjects', ['subject_id'], unique=False)
    op.alter_column('announcement_posts', 'subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('announcement_posts', 'details',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('announcement_posts', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_index('ix_announcement_posts_date', 'announcement_posts', ['date'], unique=False)
    op.create_index('ix_announcement_posts_issuer', 'announcement_posts', ['issuer'], unique=False)
    op.drop_constraint(op.f('announcement_posts_issuer_fkey'), 'announcement_posts', type_='foreignkey')
    op.create_foreign_key(None, 'announcement_posts', 'users', ['issuer'], ['id'], ondelete='SET NULL')
    op.alter_column('announcement_roles', 'announcement_post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('announcement_roles', 'for_role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=16),
               nullable=False)
    op.create_index('ix_announcement_roles_post_id', 'announcement_roles', ['announcement_post_id'], unique=False)
    op.create_unique_constraint('uq_announcement_roles', 'announcement_roles', ['announcement_post_id', 'for_role'])
    op.drop_constraint(op.f('announcement_roles_announcement_post_id_fkey'), 'announcement_roles', type_='foreignkey')
    op.create_foreign_key(None, 'announcement_roles', 'announcement_posts', ['announcement_post_id'], ['id'], ondelete='CASCADE')
    op.alter_column('attendance', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attendance', 'class_section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attendance', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('attendance', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_constraint(op.f('attendance_student_id_date_key'), 'attendance', type_='unique')
    op.create_index('ix_attendance_class_section_id', 'attendance', ['class_section_id'], unique=False)
    op.create_index('ix_attendance_section_date', 'attendance', ['class_section_id', 'date'], unique=False)
    op.create_index('ix_attendance_student_id', 'attendance', ['student_id'], unique=False)
    op.create_unique_constraint('uq_attendance_student_section_date', 'attendance', ['student_id', 'class_section_id', 'date'])
    op.drop_constraint(op.f('attendance_class_section_id_fkey'), 'attendance', type_='foreignkey')
    op.drop_constraint(op.f('attendance_student_id_fkey'), 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'class_sections', ['class_section_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'attendance', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.alter_column('class_sections', 'class_name',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('class_sections', 'section',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=8),
               nullable=False)
    op.alter_column('class_sections', 'academic_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uq_class_sections_name_section_year', 'class_sections', ['class_name', 'section', 'academic_year'])
    op.alter_column('class_subjects', 'class_section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('class_subjects', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('unique_class_subject'), 'class_subjects', type_='unique')
    op.create_index('ix_class_subjects_class_section_id', 'class_subjects', ['class_section_id'], unique=False)
    op.create_index('ix_class_subjects_subject_id', 'class_subjects', ['subject_id'], unique=False)
    op.create_unique_constraint('uq_class_subjects', 'class_subjects', ['class_section_id', 'subject_id'])
    op.drop_constraint(op.f('class_subjects_subject_id_fkey'), 'class_subjects', type_='foreignkey')
    op.drop_constraint(op.f('class_subjects_class_section_id_fkey'), 'class_subjects', type_='foreignkey')
    op.create_foreign_key(None, 'class_subjects', 'class_sections', ['class_section_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'class_subjects', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.alter_column('exam_subjects', 'exam_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exam_subjects', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exam_subjects', 'max_marks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_exam_subjects_exam_id', 'exam_subjects', ['exam_id'], unique=False)
    op.create_index('ix_exam_subjects_subject_id', 'exam_subjects', ['subject_id'], unique=False)
    op.create_unique_constraint('uq_exam_subjects', 'exam_subjects', ['exam_id', 'subject_id'])
    op.drop_constraint(op.f('exam_subjects_subject_id_fkey'), 'exam_subjects', type_='foreignkey')
    op.drop_constraint(op.f('exam_subjects_exam_id_fkey'), 'exam_subjects', type_='foreignkey')
    op.create_foreign_key(None, 'exam_subjects', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exam_subjects', 'exams', ['exam_id'], ['id'], ondelete='CASCADE')
    op.alter_column('exams', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('exams', 'class_section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_exams_class_section_id', 'exams', ['class_section_id'], unique=False)
    op.create_unique_constraint('uq_exams_section_name', 'exams', ['class_section_id', 'name'])
    op.drop_constraint(op.f('exams_class_section_id_fkey'), 'exams', type_='foreignkey')
    op.create_foreign_key(None, 'exams', 'class_sections', ['class_section_id'], ['id'], ondelete='CASCADE')
    op.alter_column('marks', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('marks', 'exam_subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('marks', 'marks_obtained',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('marks_student_id_exam_subject_id_key'), 'marks', type_='unique')
    op.create_index('ix_marks_exam_subject_id', 'marks', ['exam_subject_id'], unique=False)
    op.create_index('ix_marks_student_id', 'marks', ['student_id'], unique=False)
    op.create_unique_constraint('uq_marks_student_exam_subject', 'marks', ['student_id', 'exam_subject_id'])
    op.drop_constraint(op.f('marks_student_id_fkey'), 'marks', type_='foreignkey')
    op.drop_constraint(op.f('marks_exam_subject_id_fkey'), 'marks', type_='foreignkey')
    op.create_foreign_key(None, 'marks', 'exam_subjects', ['exam_subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'marks', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('staff', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('staff', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('staff', 'position',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               nullable=False)
    op.create_index('ix_staff_user_id', 'staff', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_subject_id'), 'staff', type_='foreignkey')
    op.drop_constraint(op.f('staff_user_id_fkey'), 'staff', type_='foreignkey')
    op.create_foreign_key(None, 'staff', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('staff', 'subject')
    op.alter_column('student_enrollments', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student_enrollments', 'class_section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student_enrollments', 'roll_no',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('student_enrollments_class_section_id_roll_no_key'), 'student_enrollments', type_='unique')
    op.create_index('ix_student_enrollments_class_section_id', 'student_enrollments', ['class_section_id'], unique=False)
    op.create_index('ix_student_enrollments_student_id', 'student_enrollments', ['student_id'], unique=False)
    op.create_unique_constraint('uq_enrollment_section_roll', 'student_enrollments', ['class_section_id', 'roll_no'])
    op.create_unique_constraint('uq_enrollment_student_section', 'student_enrollments', ['student_id', 'class_section_id'])
    op.drop_constraint(op.f('student_enrollments_class_section_id_fkey'), 'student_enrollments', type_='foreignkey')
    op.drop_constraint(op.f('student_enrollments_student_id_fkey'), 'student_enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'student_enrollments', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'student_enrollments', 'class_sections', ['class_section_id'], ['id'], ondelete='CASCADE')
    op.alter_column('students', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('students', 'father_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('students', 'mother_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('students', 'admission_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('students', 'reg_no',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_students_user_id', 'students', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'students', ['reg_no'])
    op.drop_constraint(op.f('students_user_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('subjects', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('teaching_assignments', 'staff_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teaching_assignments', 'class_subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_teaching_assignments_class_subject_id', 'teaching_assignments', ['class_subject_id'], unique=False)
    op.create_index('ix_teaching_assignments_staff_id', 'teaching_assignments', ['staff_id'], unique=False)
    op.create_unique_constraint('uq_teaching_assignments', 'teaching_assignments', ['staff_id', 'class_subject_id'])
    op.drop_constraint(op.f('teaching_assignments_class_subject_id_fkey'), 'teaching_assignments', type_='foreignkey')
    op.drop_constraint(op.f('teaching_assignments_staff_id_fkey'), 'teaching_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'teaching_assignments', 'staff', ['staff_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teaching_assignments', 'class_subjects', ['class_subject_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'teaching_assignments', type_='foreignkey')
    op.drop_constraint(None, 'teaching_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('teaching_assignments_staff_id_fkey'), 'teaching_assignments', 'staff', ['staff_id'], ['id'])
    op.create_foreign_key(op.f('teaching_assignments_class_subject_id_fkey'), 'teaching_assignments', 'class_subjects', ['class_subject_id'], ['id'])
    op.drop_constraint('uq_teaching_assignments', 'teaching_assignments', type_='unique')
    op.drop_index('ix_teaching_assignments_staff_id', table_name='teaching_assignments')
    op.drop_index('ix_teaching_assignments_class_subject_id', table_name='teaching_assignments')
    op.alter_column('teaching_assignments', 'class_subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('teaching_assignments', 'staff_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subjects', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_user_id_fkey'), 'students', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_index('ix_students_user_id', table_name='students')
    op.alter_column('students', 'reg_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'admission_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('students', 'mother_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('students', 'father_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('students', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('students', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'student_enrollments', type_='foreignkey')
    op.drop_constraint(None, 'student_enrollments', type_='foreignkey')
    op.create_foreign_key(op.f('student_enrollments_student_id_fkey'), 'student_enrollments', 'students', ['student_id'], ['id'])
    op.create_foreign_key(op.f('student_enrollments_class_section_id_fkey'), 'student_enrollments', 'class_sections', ['class_section_id'], ['id'])
    op.drop_constraint('uq_enrollment_student_section', 'student_enrollments', type_='unique')
    op.drop_constraint('uq_enrollment_section_roll', 'student_enrollments', type_='unique')
    op.drop_index('ix_student_enrollments_student_id', table_name='student_enrollments')
    op.drop_index('ix_student_enrollments_class_section_id', table_name='student_enrollments')
    op.create_unique_constraint(op.f('student_enrollments_class_section_id_roll_no_key'), 'student_enrollments', ['class_section_id', 'roll_no'], postgresql_nulls_not_distinct=False)
    op.alter_column('student_enrollments', 'roll_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_enrollments', 'class_section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_enrollments', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('staff', sa.Column('subject', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.create_foreign_key(op.f('staff_user_id_fkey'), 'staff', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_subject_id'), 'staff', 'subjects', ['subject'], ['id'])
    op.drop_index('ix_staff_user_id', table_name='staff')
    op.alter_column('staff', 'position',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('staff', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('staff', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'marks', type_='foreignkey')
    op.drop_constraint(None, 'marks', type_='foreignkey')
    op.create_foreign_key(op.f('marks_exam_subject_id_fkey'), 'marks', 'exam_subjects', ['exam_subject_id'], ['id'])
    op.create_foreign_key(op.f('marks_student_id_fkey'), 'marks', 'students', ['student_id'], ['id'])
    op.drop_constraint('uq_marks_student_exam_subject', 'marks', type_='unique')
    op.drop_index('ix_marks_student_id', table_name='marks')
    op.drop_index('ix_marks_exam_subject_id', table_name='marks')
    op.create_unique_constraint(op.f('marks_student_id_exam_subject_id_key'), 'marks', ['student_id', 'exam_subject_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('marks', 'marks_obtained',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('marks', 'exam_subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('marks', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.create_foreign_key(op.f('exams_class_section_id_fkey'), 'exams', 'class_sections', ['class_section_id'], ['id'])
    op.drop_constraint('uq_exams_section_name', 'exams', type_='unique')
    op.drop_index('ix_exams_class_section_id', table_name='exams')
    op.alter_column('exams', 'class_section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exams', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(None, 'exam_subjects', type_='foreignkey')
    op.drop_constraint(None, 'exam_subjects', type_='foreignkey')
    op.create_foreign_key(op.f('exam_subjects_exam_id_fkey'), 'exam_subjects', 'exams', ['exam_id'], ['id'])
    op.create_foreign_key(op.f('exam_subjects_subject_id_fkey'), 'exam_subjects', 'subjects', ['subject_id'], ['id'])
    op.drop_constraint('uq_exam_subjects', 'exam_subjects', type_='unique')
    op.drop_index('ix_exam_subjects_subject_id', table_name='exam_subjects')
    op.drop_index('ix_exam_subjects_exam_id', table_name='exam_subjects')
    op.alter_column('exam_subjects', 'max_marks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exam_subjects', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exam_subjects', 'exam_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'class_subjects', type_='foreignkey')
    op.drop_constraint(None, 'class_subjects', type_='foreignkey')
    op.create_foreign_key(op.f('class_subjects_class_section_id_fkey'), 'class_subjects', 'class_sections', ['class_section_id'], ['id'])
    op.create_foreign_key(op.f('class_subjects_subject_id_fkey'), 'class_subjects', 'class_subjects', ['subject_id'], ['id'])
    op.drop_constraint('uq_class_subjects', 'class_subjects', type_='unique')
    op.drop_index('ix_class_subjects_subject_id', table_name='class_subjects')
    op.drop_index('ix_class_subjects_class_section_id', table_name='class_subjects')
    op.create_unique_constraint(op.f('unique_class_subject'), 'class_subjects', ['class_section_id', 'subject_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('class_subjects', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('class_subjects', 'class_section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_class_sections_name_section_year', 'class_sections', type_='unique')
    op.alter_column('class_sections', 'academic_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('class_sections', 'section',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('class_sections', 'class_name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_student_id_fkey'), 'attendance', 'students', ['student_id'], ['id'])
    op.create_foreign_key(op.f('attendance_class_section_id_fkey'), 'attendance', 'class_sections', ['class_section_id'], ['id'])
    op.drop_constraint('uq_attendance_student_section_date', 'attendance', type_='unique')
    op.drop_index('ix_attendance_student_id', table_name='attendance')
    op.drop_index('ix_attendance_section_date', table_name='attendance')
    op.drop_index('ix_attendance_class_section_id', table_name='attendance')
    op.create_unique_constraint(op.f('attendance_student_id_date_key'), 'attendance', ['student_id', 'date'], postgresql_nulls_not_distinct=False)
    op.alter_column('attendance', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('attendance', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('attendance', 'class_section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attendance', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'announcement_roles', type_='foreignkey')
    op.create_foreign_key(op.f('announcement_roles_announcement_post_id_fkey'), 'announcement_roles', 'announcement_posts', ['announcement_post_id'], ['id'])
    op.drop_constraint('uq_announcement_roles', 'announcement_roles', type_='unique')
    op.drop_index('ix_announcement_roles_post_id', table_name='announcement_roles')
    op.alter_column('announcement_roles', 'for_role',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('announcement_roles', 'announcement_post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'announcement_posts', type_='foreignkey')
    op.create_foreign_key(op.f('announcement_posts_issuer_fkey'), 'announcement_posts', 'users', ['issuer'], ['id'])
    op.drop_index('ix_announcement_posts_issuer', table_name='announcement_posts')
    op.drop_index('ix_announcement_posts_date', table_name='announcement_posts')
    op.alter_column('announcement_posts', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('announcement_posts', 'details',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('announcement_posts', 'subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_staff_subjects_subject_id', table_name='staff_subjects')
    op.drop_index('ix_staff_subjects_staff_id', table_name='staff_subjects')
    op.drop_table('staff_subjects')
    # ### end Alembic commands ###
