"""Updated Exam table to store date of the examination

Revision ID: 786122f22820
Revises: 7e322c311a6a
Create Date: 2026-05-02 02:15:52.747056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786122f22820'
down_revision: Union[str, Sequence[str], None] = '7e322c311a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'date')
    # ### end Alembic commands ###
