"""Updated exams table to include exam_type and created_by information

Revision ID: 8efdf9984b6d
Revises: 0d8aec64f119
Create Date: 2026-05-02 19:16:56.819836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8efdf9984b6d'
down_revision: Union[str, Sequence[str], None] = '0d8aec64f119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('exam_type', sa.String(length=25), server_default='official', nullable=True))
    op.add_column('exams', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exams', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_column('exams', 'created_by')
    op.drop_column('exams', 'exam_type')
    # ### end Alembic commands ###
