"""Made exam status column and exam_type column non-nullable

Revision ID: cd627adcb941
Revises: 5203b02a8c1d
Create Date: 2026-05-04 19:43:32.170379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd627adcb941'
down_revision: Union[str, Sequence[str], None] = '5203b02a8c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exams', 'exam_type',
               existing_type=sa.VARCHAR(length=25),
               nullable=False,
               existing_server_default=sa.text("'official'::character varying"))
    op.alter_column('exams', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exams', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('exams', 'exam_type',
               existing_type=sa.VARCHAR(length=25),
               nullable=True,
               existing_server_default=sa.text("'official'::character varying"))
    # ### end Alembic commands ###
