"""baseline schema

Revision ID: e29651c2660b
Revises: 
Create Date: 2026-05-04 23:45:10.764972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29651c2660b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=64), nullable=False),
    sa.Column('section', sa.String(length=8), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_name', 'section', 'academic_year', name='uq_class_sections_name_section_year')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.CheckConstraint("role IN ('student', 'teacher', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_admins_user_id', 'admins', ['user_id'], unique=False)
    op.create_table('announcement_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.Column('issuer', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.ForeignKeyConstraint(['issuer'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_announcement_posts_date', 'announcement_posts', ['date'], unique=False)
    op.create_index('ix_announcement_posts_issuer', 'announcement_posts', ['issuer'], unique=False)
    op.create_table('class_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_section_id'], ['class_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_section_id', 'subject_id', name='uq_class_subjects')
    )
    op.create_index('ix_class_subjects_class_section_id', 'class_subjects', ['class_section_id'], unique=False)
    op.create_index('ix_class_subjects_subject_id', 'class_subjects', ['subject_id'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('class_section_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exam_type', sa.String(length=25), server_default='official', nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'completed')", name='ck_exam_status'),
    sa.ForeignKeyConstraint(['class_section_id'], ['class_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_section_id', 'name', name='uq_exams_section_name')
    )
    op.create_index('ix_exams_class_section_id', 'exams', ['class_section_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_staff_user_id', 'staff', ['user_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('father_name', sa.String(length=128), nullable=False),
    sa.Column('mother_name', sa.String(length=128), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('reg_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reg_no'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_students_user_id', 'students', ['user_id'], unique=False)
    op.create_table('announcement_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_post_id', sa.Integer(), nullable=False),
    sa.Column('for_role', sa.String(length=16), nullable=False),
    sa.CheckConstraint("for_role IN ('student', 'teacher', 'admin')", name='ck_announcement_roles_role'),
    sa.ForeignKeyConstraint(['announcement_post_id'], ['announcement_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_post_id', 'for_role', name='uq_announcement_roles')
    )
    op.create_index('ix_announcement_roles_post_id', 'announcement_roles', ['announcement_post_id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_section_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.CheckConstraint("status IN ('present', 'absent')", name='ck_attendance_status'),
    sa.ForeignKeyConstraint(['class_section_id'], ['class_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'class_section_id', 'date', name='uq_attendance_student_section_date')
    )
    op.create_index('ix_attendance_class_section_id', 'attendance', ['class_section_id'], unique=False)
    op.create_index('ix_attendance_section_date', 'attendance', ['class_section_id', 'date'], unique=False)
    op.create_index('ix_attendance_student_id', 'attendance', ['student_id'], unique=False)
    op.create_table('exam_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('class_subject_id', sa.Integer(), nullable=False),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_marks > 0', name='ck_exam_subjects_max_marks'),
    sa.ForeignKeyConstraint(['class_subject_id'], ['class_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'class_subject_id', name='uq_exam_subjects')
    )
    op.create_index('ix_exam_subjects_exam_id', 'exam_subjects', ['exam_id'], unique=False)
    op.create_index('ix_exam_subjects_subject_id', 'exam_subjects', ['class_subject_id'], unique=False)
    op.create_table('staff_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'subject_id', name='uq_staff_subjects')
    )
    op.create_index('ix_staff_subjects_staff_id', 'staff_subjects', ['staff_id'], unique=False)
    op.create_index('ix_staff_subjects_subject_id', 'staff_subjects', ['subject_id'], unique=False)
    op.create_table('student_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_section_id', sa.Integer(), nullable=False),
    sa.Column('roll_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_section_id'], ['class_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_section_id', 'roll_no', name='uq_enrollment_section_roll'),
    sa.UniqueConstraint('student_id', 'class_section_id', name='uq_enrollment_student_section')
    )
    op.create_index('ix_student_enrollments_class_section_id', 'student_enrollments', ['class_section_id'], unique=False)
    op.create_index('ix_student_enrollments_student_id', 'student_enrollments', ['student_id'], unique=False)
    op.create_table('teaching_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('class_subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_subject_id'], ['class_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'class_subject_id', name='uq_teaching_assignments')
    )
    op.create_index('ix_teaching_assignments_class_subject_id', 'teaching_assignments', ['class_subject_id'], unique=False)
    op.create_index('ix_teaching_assignments_staff_id', 'teaching_assignments', ['staff_id'], unique=False)
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exam_subject_id', sa.Integer(), nullable=False),
    sa.Column('marks_obtained', sa.Integer(), nullable=False),
    sa.CheckConstraint('marks_obtained >= 0', name='ck_marks_obtained_non_negative'),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'exam_subject_id', name='uq_marks_student_exam_subject')
    )
    op.create_index('ix_marks_exam_subject_id', 'marks', ['exam_subject_id'], unique=False)
    op.create_index('ix_marks_student_id', 'marks', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_marks_student_id', table_name='marks')
    op.drop_index('ix_marks_exam_subject_id', table_name='marks')
    op.drop_table('marks')
    op.drop_index('ix_teaching_assignments_staff_id', table_name='teaching_assignments')
    op.drop_index('ix_teaching_assignments_class_subject_id', table_name='teaching_assignments')
    op.drop_table('teaching_assignments')
    op.drop_index('ix_student_enrollments_student_id', table_name='student_enrollments')
    op.drop_index('ix_student_enrollments_class_section_id', table_name='student_enrollments')
    op.drop_table('student_enrollments')
    op.drop_index('ix_staff_subjects_subject_id', table_name='staff_subjects')
    op.drop_index('ix_staff_subjects_staff_id', table_name='staff_subjects')
    op.drop_table('staff_subjects')
    op.drop_index('ix_exam_subjects_subject_id', table_name='exam_subjects')
    op.drop_index('ix_exam_subjects_exam_id', table_name='exam_subjects')
    op.drop_table('exam_subjects')
    op.drop_index('ix_attendance_student_id', table_name='attendance')
    op.drop_index('ix_attendance_section_date', table_name='attendance')
    op.drop_index('ix_attendance_class_section_id', table_name='attendance')
    op.drop_table('attendance')
    op.drop_index('ix_announcement_roles_post_id', table_name='announcement_roles')
    op.drop_table('announcement_roles')
    op.drop_index('ix_students_user_id', table_name='students')
    op.drop_table('students')
    op.drop_index('ix_staff_user_id', table_name='staff')
    op.drop_table('staff')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_exams_class_section_id', table_name='exams')
    op.drop_table('exams')
    op.drop_index('ix_class_subjects_subject_id', table_name='class_subjects')
    op.drop_index('ix_class_subjects_class_section_id', table_name='class_subjects')
    op.drop_table('class_subjects')
    op.drop_index('ix_announcement_posts_issuer', table_name='announcement_posts')
    op.drop_index('ix_announcement_posts_date', table_name='announcement_posts')
    op.drop_table('announcement_posts')
    op.drop_index('ix_admins_user_id', table_name='admins')
    op.drop_table('admins')
    op.drop_table('users')
    op.drop_table('subjects')
    op.drop_table('class_sections')
    # ### end Alembic commands ###
